[tasks.css]
command = "bunx"
args = ["unocss", "--watch", "**/*.rs", "-o", "./static/uno.css"]

[tasks.server]
command = "cargo"
args = ["run", "--bin", "server", "--features", "ssr"]

[tasks.serve]
command = "trunk"
args = ["serve", "--features", "hydrate", "-w", "./"]

[tasks.dev]
run_task = { name = ["css", "serve", "server"], parallel = true }
