[package]
name = "switch"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.21.0"
yewlish-utils = "0.1.2"
yewlish-attr-passer = "0.1.2"
log = "0.4.22"
