[package]
name = "popover"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.21.0"
web-sys = { version = "0.3.69", features = ["Element", "DomRect"] }
log = "0.4.21"
attr_passer = { path = "../attr_passer" }
presence = { path = "../presence" }
utils = { path = "../utils" }
