[package]
name = "virtual-list"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.21.0"
log = "0.4.21"
web-sys = { version = "0.3.69", features = ["HtmlElement"] }
