[package]
name = "listbox"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.22"
web-sys = "0.3.69"
yew = "0.21.0"
presence = { path = "../presence" }
utils = { path = "../utils" }
